---
logging:
  format: '%{color}%{time:2006-01-02 15:04:05.000 MST} [%{module}] %{shortfunc} -> %{level:.4s} %{id:03x}%{color:reset} %{message}'

peer:
  id: Org1.peer0
  networkId: xh7fstndcrflheodreernvvvxy
  address: 127.0.0.1:26512
  addressAutoDetect: true
  listenAddress: 127.0.0.1:26512
  chaincodeListenAddress: 0.0.0.0:26513
  keepalive:
    minInterval: 60s
    client:
      interval: 60s
      timeout: 20s
    deliveryClient:
      interval: 60s
      timeout: 20s
  gossip:
    bootstrap: 127.0.0.1:26512
    endpoint: 127.0.0.1:26512
    externalEndpoint: 127.0.0.1:26512
    useLeaderElection: false
    orgLeader: true
    membershipTrackerInterval: 5s
    maxBlockCountToStore: 10
    maxPropagationBurstLatency: 10ms
    maxPropagationBurstSize: 10
    propagateIterations: 1
    propagatePeerNum: 3
    pullInterval: 4s
    pullPeerNum: 3
    requestStateInfoInterval: 4s
    publishStateInfoInterval: 4s
    stateInfoRetentionInterval:
    publishCertPeriod: 10s
    dialTimeout: 3s
    connTimeout: 2s
    recvBuffSize: 20
    sendBuffSize: 200
    digestWaitTime: 1s
    requestWaitTime: 1500ms
    responseWaitTime: 2s
    aliveTimeInterval: 5s
    aliveExpirationTimeout: 25s
    reconnectInterval: 25s
    election:
      startupGracePeriod: 15s
      membershipSampleInterval: 1s
      leaderAliveThreshold: 10s
      leaderElectionDuration: 5s
    pvtData:
      pullRetryThreshold: 7s
      transientstoreMaxBlockRetention: 1000
      pushAckTimeout: 3s
      btlPullMargin: 10
      reconcileBatchSize: 10
      reconcileSleepInterval: 10s
      reconciliationEnabled: true
      skipPullingInvalidTransactionsDuringCommit: false
      implicitCollectionDisseminationPolicy:
        requiredPeerCount: 0
        maxPeerCount: 1
    state:
       enabled: false
       checkInterval: 10s
       responseTimeout: 3s
       batchSize: 10
       blockBufferSize: 20
       maxRetries: 3
  events:
    address: 127.0.0.1:26514
    buffersize: 100
    timeout: 10ms
    timewindow: 15m
    keepalive:
      minInterval: 60s
  tls:
    enabled: true
    clientAuthRequired: false
    cert:
      file: /Users/wlahti/gopath/src/github.com/hyperledger/fabric/demo/config/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
    key:
      file: /Users/wlahti/gopath/src/github.com/hyperledger/fabric/demo/config/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
    clientCert:
      file: /Users/wlahti/gopath/src/github.com/hyperledger/fabric/demo/config/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
    clientKey:
      file: /Users/wlahti/gopath/src/github.com/hyperledger/fabric/demo/config/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
    rootcert:
      file: /Users/wlahti/gopath/src/github.com/hyperledger/fabric/demo/config/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
    clientRootCAs:
      files:
      - /Users/wlahti/gopath/src/github.com/hyperledger/fabric/demo/config/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
  authentication:
    timewindow: 15m
  fileSystemPath: filesystem
  BCCSP:
    Default: SW
    SW:
      Hash: SHA2
      Security: 256
      FileKeyStore:
        KeyStore:
  mspConfigPath: /Users/wlahti/gopath/src/github.com/hyperledger/fabric/demo/config/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp
  localMspId: Org1MSP
  deliveryclient:
    reconnectTotalTimeThreshold: 3600s
  localMspType: bccsp
  profile:
    enabled:     false
    listenAddress: 127.0.0.1:0
  handlers:
    authFilters:
    - name: DefaultAuth
    - name: ExpirationCheck
    decorators:
    - name: DefaultDecorator
    endorsers:
      escc:
        name: DefaultEndorsement
    validators:
      vscc:
        name: DefaultValidation
  validatorPoolSize:
  discovery:
    enabled: true
    authCacheEnabled: true
    authCacheMaxSize: 1000
    authCachePurgeRetentionRatio: 0.75
    orgMembersAllowedAccess: false
  limits:
    concurrency:
      endorserService: 100
      deliverService: 100

vm:
  endpoint: unix:///var/run/docker.sock
  docker:
    tls:
      enabled: false
      ca:
        file: docker/ca.crt
      cert:
        file: docker/tls.crt
      key:
        file: docker/tls.key
    attachStdout: true
    hostConfig:
      NetworkMode: host
      LogConfig:
        Type: json-file
        Config:
          max-size: "50m"
          max-file: "5"
      Memory: 2147483648

chaincode:
  builder: $(DOCKER_NS)/fabric-ccenv:$(PROJECT_VERSION)
  pull: false
  golang:
    runtime: $(DOCKER_NS)/fabric-baseos:$(PROJECT_VERSION)
    dynamicLink: false
  java:
    runtime: $(DOCKER_NS)/fabric-javaenv:latest
  node:
    runtime: $(DOCKER_NS)/fabric-nodeenv:latest
  installTimeout: 300s
  startuptimeout: 300s
  executetimeout: 30s
  mode: net
  keepalive: 0
  system:
    _lifecycle: enable
    cscc:       enable
    lscc:       enable
    qscc:       enable
  logging:
    level:  info
    shim:   warning
    format: '%{color}%{time:2006-01-02 15:04:05.000 MST} [%{module}] %{shortfunc} -> %{level:.4s} %{id:03x}%{color:reset} %{message}'
  externalBuilders:
    - path: /Users/wlahti/gopath/src/github.com/hyperledger/fabric/integration/externalbuilders/golang
      name: golang
      propagateEnvironment:
         - GOPROXY

ledger:
  blockchain:
  state:
    stateDatabase: goleveldb
    couchDBConfig:
      couchDBAddress: 127.0.0.1:5984
      username:
      password:
      maxRetries: 3
      maxRetriesOnStartup: 10
      requestTimeout: 35s
      queryLimit: 10000
      maxBatchUpdateSize: 1000
      warmIndexesAfterNBlocks: 1
  history:
    enableHistoryDatabase: true

operations:
  listenAddress: 127.0.0.1:26516
  tls:
    enabled: true
    cert:
      file: /Users/wlahti/gopath/src/github.com/hyperledger/fabric/demo/config/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
    key:
      file: /Users/wlahti/gopath/src/github.com/hyperledger/fabric/demo/config/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
    clientAuthRequired: false
    clientRootCAs:
      files:
      - /Users/wlahti/gopath/src/github.com/hyperledger/fabric/demo/config/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
metrics:
  provider: prometheus
  statsd:
    network: udp
    address: 127.0.0.1:8125
    writeInterval: 5s
    prefix: org1_peer0
