---
OrdererOrgs:
- Name: OrdererOrg
  Domain: example.com
  EnableNodeOUs: false
  CA:
    Hostname: ca
  Specs:
  - Hostname: orderer1
    SANS:
    - localhost
    - 127.0.0.1
    - ::1

PeerOrgs:
- Name: Org1
  Domain: org1.example.com
  EnableNodeOUs: true
  CA:
    hostname: ca
    SANS:
    - localhost
    - 127.0.0.1
    - ::1
  Users:
    Count: 2
  Specs:
  - Hostname: peer0
    SANS:
    - localhost
    - 127.0.0.1
    - ::1
- Name: Org2
  Domain: org2.example.com
  EnableNodeOUs: true
  CA:
    hostname: ca
    SANS:
    - localhost
    - 127.0.0.1
    - ::1
  Users:
    Count: 2
  Specs:
  - Hostname: peer0
    SANS:
    - localhost
    - 127.0.0.1
    - ::1
